# This is a basic workflow to help you get started with Actions

name: Basic - Robot Udemy - Web

on:
  push:
    branches: [ master-udemy ]
  pull_request:
    branches: [ master-udemy ]

  workflow_dispatch:
jobs:
  # build:
  job1:
    name: Setup Machine
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Dependencies
        run: |
            sudo apt-get install -y xvfb ca-certificates net-tools netcat gnupg ffmpeg libgtk-3-0 libgdk-pixbuf2.0-dev libxcomposite-dev libdbus-glib-1-2 libatk-bridge2.0-0 wget libgbm1 libnss3 libxss1 libasound2 
      - name: Setup Node
        run: |
          curl -fsSL https://deb.nodesource.com/setup_14.x | sudo -E bash -
          sudo apt-get install -y nodejs
      - name: Setup python
        run: |
          python -m pip install --upgrade pip
      - name: Setup Requirements
        run: |
          pip install -r requirements.txt    
      - name: Run Robot Init
        run: |
          rfbrowser init
  job2:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: job1
    steps:

      - name: Run Robot Test
        run: |
          robot -d ./log basic/SuiteTest/Tests/

      # - uses: actions/checkout@v2

      # - uses: actions/download-artifact@v2
      #   with:
      #     name: my-artifact
      #     path: path/to/artifact

      # - name: Display structure of downloaded files
      #   run: ls -R
      #   working-directory: path/to/artifact
        
      # - uses: actions/download-artifact@v2
      #   with:
      #     name: my-artifact
      #     path: ~/download/path

      - name: Upload a Build Artifact Logs
        uses: actions/upload-artifact@v2.2.3
        with:
          name: Robot Logs 
          path: log/


